; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27034.0 

	TITLE	D:\Git\Tp3_MiniProjetRaven\Raven\VS2015\Buckland_Chapter7 to 10_Raven\goals\Goal_SayPhrase.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
